---
title: "Simulation study of statistical methods for comparing groups"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Examples and informal evaluations of various statistical significance tests for comparing observations generated from different distributions and families.

```{r repo-info, results='asis'}
repo_info <- data.frame(
  status = "work in progress",
  content = "[CC BY-SA](https://creativecommons.org/licenses/by-sa/4.0/)",
  code = "[MIT](LICENSE)",
  stringsAsFactors = FALSE
)
knitr::kable(repo_info, format = "markdown")
```

## Setup

Installing dependencies in R:

```R
install.packages(c(
  "rmarkdown", "tidyverse", "remotes",
  "ggdist", "gt", "patchwork"
))
remotes::install_github("rstudio/distill")
```

Knitting the R Markdown source document to an HTML page, which requires a local copy of [Wikipedia Context Cards](https://github.com/joakin/context-cards):

``` bash
# wget https://unpkg.com/context-cards/dist/context-cards.js
$ R -e "rmarkdown::render('index.Rmd')"
```
